<a href="https://colab.research.google.com/github/Rafirai/uts-pembelajaran-mesin/blob/main/UTS_PEMBELAJARAN_MESIN_1197050108_RAFIRAIHERYANTO_E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UTS Pembelajaran Mesin




Nim, Nama, Kelas : 1197050108, RAFI RAI HERYANTO, E

#Topik Mini Riset

KLASIFIKASI TYPE MOBIL DARI DATATRAIN MENGGUNAKAN ALGORITMA NAIVE BAYES

#Business Understanding
#Permasalahan :

1.   Rafi adalah pemilik showroom mobil
2.   showroom tersebut memiliki masalah dalam klasifikasi type mobil yang akan dijual
3. showroom tersebut ingin mengetahui type mobil yang akan dijual



#Tujuan :
klasifikasi type mobil otomatis dari ciri yang diberikan

#Timeline :


*   18/04/2022 : Penentuan tema riset
* 19/04/2022 : Pembuatan Business Understanding
* 20/04/2022 : Melakukan Data Understanding dan Data Preparation
* 22/04/2022 : Modeling dan Evaluasi




In [1]:
import pandas as pd
import numpy as np

In [45]:
datatrain = pd.read_csv('https://raw.githubusercontent.com/Rafirai/uts-pembelajaran-mesin/main/data_cars.csv')
datatrain = datatrain.apply(pd.to_numeric)
datatrain.head()


id  income  cars  type
0   12312    3000     1     1
1  345346    5000     2     1
2    5675    8000     3     2
3   45745    8000     4     2
4    4574    4000     1     1

In [46]:
datatrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   income  5 non-null      int64
 2   cars    5 non-null      int64
 3   type    5 non-null      int64
dtypes: int64(4)
memory usage: 288.0 bytes


In [48]:
x = datatrain.drop (["type"], axis = 1)
y = datatrain ["type"]

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [51]:
x_test

id  income  cars
1  345346    5000     2

In [52]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()

In [53]:
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([2., 2.])

In [54]:
y_pred = nbtrain.predict(x_test)
y_pred

array([1])

In [55]:
np.array(y_test)

array([1])

In [56]:
nbtrain.predict_proba(x_test)

array([[1., 0.]])

In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[1]])

In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         1

    accuracy                           1.00         1
   macro avg       1.00      1.00      1.00         1
weighted avg       1.00      1.00      1.00         1

